 ### Lab 1 <br/> CSCN8000 - Artificial Intelligence Algorithms and Mathematics <br/> Ricardo Mohammed (7500382) <br/> September 21st, 2026
 ---

## PART A

### 1. This is a Jupyter notebook that demonstrates some Numpy operations.

### 2. Create an Array that starts from integer values 1 to 20.

We use np.arange(1, 21, 3) to create an array whose first element is 1, then each subsequent element increments the previous one by 3. We go up to but not including 21. 

In [25]:
import numpy as np

arr = np.arange(1, 21, 3)
print(arr)


[ 1  4  7 10 13 16 19]


### 3. Create a new array of shape 3 with random numbers between 0 and 1.

We use np.random.rand(n) to create an array of size n whose elements are random numbers between 0 and 1.

In [26]:
# Create an array of size 3, with random numbers between 0 and 1
random_array = np.random.rand(3)
print(random_array)

[0.69427032 0.64328022 0.47524894]


### 4. Create a 2D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

We create the 2D array as specified, and then perform slice opertaions to get the first two rows and last two rows.

In [27]:
# Create a two-dimensional array with the following values: [10, 20, 45], [30, 12, 16], [42, 17, 56]
two_dimensional_array = np.array([[10, 20, 45],
                                  [30, 12, 16],
                                  [42, 17, 56]])

# Slice the 2D array to get the first two rows
sliced_array = two_dimensional_array[:2]
print("First two rows:")
print(sliced_array)

print("================================")

# Slice the 2D array to get the last two rows
sliced_array = two_dimensional_array[-2:]
print("Last two rows:")
print(sliced_array)


First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


### 5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

We create two 2x2 arrays, then stack and unstack them vertically using np.vstack() and np.vsplit(). We also stack and unstack them horizontally using np.hstack() and np.hsplit().

In [ ]:
output_divider = "\n===============================\n"

# Create two 2D arrays, then stack them vertically
array_a = np.array([[1,2],
                    [3,4]])

array_b = np.array([[5,6],
                    [7,8]])

print("Array A:")
print(array_a)
print("Array B:")
print(array_b )
print(output_divider)


# Stack the two 2D arrays vertically
vertical_stack = np.vstack((array_a, array_b))
print("Vertical Stack:")
print(vertical_stack)
print(output_divider)


# Stack the two 2D arrays horizontally
horizontal_stack = np.hstack((array_a, array_b))
print("Horizontal Stack:")
print(horizontal_stack)
print(output_divider)


# Split the 2D arrays into two equal parts vertically
original_a, original_b = np.vsplit(vertical_stack, 2)
print("Split Vertical:")
print("Original Array A:")
print(original_a)
print("Original Array B:")
print(original_b)
print(output_divider)
    
# Split the 2D arrays into two equal parts horizontally
original_a, original_b = np.hsplit(horizontal_stack, 2)
print("Split Horizontal:")
print("Original Array A:")
print(original_a)
print("Original Array B:")
print(original_b)



Array A:
[[1 2]
 [3 4]]
Array B:
[[5 6]
 [7 8]]


Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


Split Vertical:
Original Array A:
[[1 2]
 [3 4]]
Original Array B:
[[5 6]
 [7 8]]


Split Horizontal:
Original Array A:
[[1 2]
 [3 4]]
Original Array B:
[[5 6]
 [7 8]]


### 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

We create two matrices X and Y . In this case, because the number of columns in X equals the number of rows in Y, the matrix multiplication X(Y) is possible. In the case of X(Z), the number of rows in Z is less than the number of columns in X. So the try/except block should catch an error. Due to a probable environment issue, the error message does not appear. But the math holds.

In [ ]:
# Arrays X and Y as specified
X = np.array([[5, 7, 2],
              [4, 5, 6], 
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2], 
              [4, 2]])

# Perform matrix multiplication using np.dot()
result = np.dot(X, Y)

print("Matrix Multiplication Result:")
print(result)
print(output_divider)


# In order for X(Z) to be valid, the number of columns in X must equal the number of rows in Z.
# To create an invalid matrix multiplication, we can define a new matrix Y with a different ...
#  ... number of rows than the number of columns in X.

Z = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    invalid_result = np.dot(X, Z)
    print("Invalid Matrix Multiplication Result:")
    print(invalid_result)
except ValueError as e:
    print("Error during matrix multiplication:", e)

## The code does not print a result due to a possible kernel issue, but the math holds that it would produce an error


Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]




### 7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

Two 1D vectors are created, x and y. We examine the shape of the vector, then reshape it to a matrix of (3,1). Then we confirm the dimensions of the resulting matrices.

In [23]:
X = np.array([-2, -1, -8])
Y = np.array([3, 1, -2])

# Find the shape of X
print("Shape of X:", X.shape)
print(output_divider)

# Reshape X to a 3x1 array
X_reshaped = X.reshape(3, 1)
print("Reshaped X:")
print(X_reshaped)
print(output_divider)

# Reshape Y to a 3x1 array
Y_reshaped = Y.reshape(3, 1)
print("Reshaped Y:")
print(Y_reshaped)
print("\n")
print ("Dimensions of reshaped Y:", Y_reshaped.ndim)




Shape of X: (3,)


Reshaped X:
[[-2]
 [-1]
 [-8]]


Reshaped Y:
[[ 3]
 [ 1]
 [-2]]


Dimensions of reshaped Y: 2


### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

A 3x3 matrix is created, as well as a 1D vector. The output shows the result of subtracting and multiplying the vector from the matrix, using broadcasting.

In [22]:
# Broadcasting is a feature in NumPy that allows for operations between arrays of different shapes.
# It automatically expands the smaller array to match the shape of the larger array,
# enabling element-wise operations without the need for explicit replication.

# 3D matrix with shape (3, 3)
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],   
                       [7, 8, 9]])

# 1D vector with shape (3,)
vector = np.array([10, 20, 30])

# Subtract the vector from each row of the matrix using broadcasting
subtraction_result = matrix_3x3 - vector
print("Matrix 3x3:")
print(matrix_3x3)
print("\nVector:")
print(vector)
print(output_divider)
print("Subtraction Result:")
print(subtraction_result)
print(output_divider)

# Multiplication of a 3D matrix with a 1D vector using broadcasting
multiplication_result = matrix_3x3 * vector
print("Multiplication Result:")
print(multiplication_result)


Matrix 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
[10 20 30]


Subtraction Result:
[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


Multiplication Result:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


## PART B
### 1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. <br/>
###     1. 2x1+3x2-4x3=6,x1-4x2=8 <br/> 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8 

In each system, we have 3 unknown variables but only two equations. This means there will be infinitely many solutions. 

In [28]:
import numpy as np

# System 1: 2 equations, 3 variables
A1 = np.array([[2, 3, -4], [1, -4, 0]])
b1 = np.array([6, 8])

# System 2: 2 equations, 3 variables
A2 = np.array([[3, -4, 5], [-1, 2, -4]])
b2 = np.array([10, 8])

print(f"System 1 Matrix Shape: {A1.shape}")
print(f"System 2 Matrix Shape: {A2.shape}")

System 1 Matrix Shape: (2, 3)
System 2 Matrix Shape: (2, 3)
